added blog 2
STAC-IITMandi/Blog pull request #1
Opened 2019-07-25 15:03 UTC by abhijeetmanhas

I have added second blog titled "in a parallel universe" which was already published on STAC medium. 
@shreyasbapat please review it.
![Screenshot (62)](https://user-images.githubusercontent.com/43112347/61885146-fe2ec800-af1a-11e9-993d-87b76d2890a4.png)

2019-07-25 15:27 UTC, shreyasbapat commented
Why are 37 file changes?

2019-07-25 15:34 UTC, shreyasbapat requested changes
Some questions, though I don't get to understand why there are so many changes

2019-07-25 15:34 UTC, shreyasbapat commented on _site/CNAME
> +blog.stac-iitmandi.org
CNAME is already added

2019-07-25 15:34 UTC, shreyasbapat commented on _site/COPYING
> +Copyright (c) 2019 STAC Web Development Team, WowThemes.net
No need to add this either

2019-07-25 15:34 UTC, shreyasbapat commented on _site/about.html
> +<meta property="og:url" content="http://localhost:4000/about" />
why localhost

2019-07-25 17:58 UTC, abhijeetmanhas commented
I found most of the changes are in _site folder, which is formed when you build or compile your blog, _site and cache should be put in .gitignore file which didn't pre-existed, I will do this know.

2019-07-25 18:36 UTC, abhijeetmanhas commented
> Why are 37 file changes?

Now only 4. I have added .gitignore.

2019-07-26 05:55 UTC, shreyasbapat commented on _posts/2018-07-08-In-a-Parallel-Universe.md
> +Written by: Anant Mishra
Remove this line

2019-07-27 22:27 UTC, merged